version: '3.7'
services:
  axon:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro

volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config: