spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
server:
  port: 0